### ISSUE TITLE
Migrate from Ionic to Angular app - Core Functionality

### ISSUE THREAD

**Issue by FugueWeb** [FugueWeb/fugue#2]
## Task

1. Convert core functionality of [existing app](https://fugueweb.com/fugue/#/app/cover/tabs) from Ionic into Angular/Angular Material app using this repo as a starting point. You don't need to make it look pretty, just wire up the features.

### Home Page

* Add [tabs](https://material.angular.io/components/tabs/examples) as a footer
* `Cover` tab - add image slider
* `Definition` and `Author` tab - thumbnail images should open as modal

### Example page (`Prelude`)

* Using `/src/assets/data/prelude.json`, pull in the HTML, iterate over the objects as multiple pages
* Using [Swipe JS](https://github.com/lyfeyaj/swipe) | [docs](https://swipe.js.org/), enable a swipe capability between the pages. When user swipes left/right, it should change the page
* Add [paginator](https://material.angular.io/components/paginator/examples) showing the total number of pages
* In the header, use `localstorage` to enable bookmarking capability (bookmarks show up on `Bookmarks` page and may be deleted)

## Required skills

* Proficient understanding of Angular as well as Angular Material. Please include reference to other projects you have done in Angular as a reference. Knowledge of Ionic framework also a plus. 
* Knowledge of progressive web apps and local storage capabilities (nothing too intense, just some bookmarks)
* Knowledge of Web3 integration - This is not an immediate goal, but a feature I want to integrate into the app later
* Knowledge of integrating APIs - Specifically the app uses APIs with SoundCloud as well as Google Maps, and it's possible it may eventually use a blockchain type API like Etherscan or Infura.

## Other considerations

My primary motivation here is to outsource the conversion between frameworks as well as some of the core development. Ultimately the goal is to get the app into a state that allows me to maintain it going forward. Changes should be submitted back to this repo as pull requests using the pull request template provided.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 250.0 DAI (250.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,860,091.27 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 4 weeks from now.
Please review their action plans below:


**1) [santiagogregory](https://gitcoin.co/santiagogregory) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?mutate_worker_action=approve&worker=santiagogregory) | [reject worker](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?mutate_worker_action=reject&worker=santiagogregory))_.**

I am familiar with Angular and Material design, and will be able to migrate this.
**2) [annnoo](https://gitcoin.co/annnoo) has been approved to start work.**

Good evening,

we have discussed  this Gitcoin task in the meeting regarding the consulation bounty. 
I am very interested and could  start working on it in the following days.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086).

**Comment by gitcoinbot** [comment]
@annnoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=1) | [3 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=3) | [5 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=5) | [10 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=10) | [100 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=100)

**Comment by gitcoinbot** [comment]
@annnoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=1) | [3 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=3) | [5 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=5) | [10 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=10) | [100 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=100)

**Comment by gitcoinbot** [comment]
@annnoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=1) | [3 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=3) | [5 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=5) | [10 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=10) | [100 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=100)

**Comment by gitcoinbot** [comment]
@annnoo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=1) | [3 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=3) | [5 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=5) | [10 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=10) | [100 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@annnoo due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=1) | [3 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=3) | [5 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=5) | [10 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=10) | [100 days](https://gitcoin.co/issue/FugueWeb/fugue/2/100026086?snooze=100)

**Comment by annnoo** [comment]
Good Evening,
as I have discussed the issue yesterday with fugue, i am still working on it (but was unable to comment on this issue) It will be probably finished today/in the upcommign day.

**Comment by annnoo** [comment]
Hey @FugueWeb ,

Some parts were a tougher road than i thought and took a bit longer, but now the issue is at a point, where I am confident to say, that there is now a good base for all the upcoming features.
I described everything that has been done and how the json-file should change. There a still a few small todos, because i focused on creating a good base for the different features (mostly "css" or design related). I wrote them down in the comment aswell.
 
https://github.com/FugueWeb/fugue/pull/4#issuecomment-892003924 

If everything is fine for you, i will submit the work on this task on gitcoin
